name: flutter_material_design_icons
description: This package provides over 7000+ material icons from the Material Design Icons (MDI) project.
version: 1.1.7367
homepage: https://github.com/FaFre/flutter_material_design_icons

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.4
  builder:
    path: ../builder
  custom_lint: ^0.5.2
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

dependency_overrides:
  code_builder:
    git:
      url: https://github.com/FaFre/code_builder.git
      ref: enum_named_arguments

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Material Design Icons
      fonts:
        - asset: assets/materialdesignicons-webfont.ttf
