name: flutter_material_design_icons_workspace

scripts:
  generate:
    run: cd packages/material_design_icons/ && dart run build_runner build -d
  rasterize:
    run: cd packages/rasterizer && flutter run -d linux lib/main.dart
    description: Install dependencies to generate font
  build-app:
    run: output=$(pwd)/docs/icon_app/ &&
      cd packages/material_design_icons/example/ &&
      flutter pub get && flutter build web --release -o $output

packages:
  - "packages/**"
