name: example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_material_design_icons:
    path: ../
  hooks_riverpod: ^2.3.6

dev_dependencies:
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true
