name: builder
description: Internal icon builder
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  build: ^2.4.0
  code_builder:
    git:
      url: https://github.com/FaFre/code_builder.git
      ref: enum_named_arguments
  json_annotation: ^4.8.1
  source_gen: ^1.3.2

dev_dependencies:
  build_runner: ^2.4.4
  build_test: ^2.1.7
  custom_lint: ^0.5.2
  json_serializable: ^6.7.0
  lint: ^2.1.2
  test: ^1.21.0

dependency_overrides:
  code_builder:
    git:
      url: https://github.com/FaFre/code_builder.git
      ref: enum_named_arguments
